### ISSUE TITLE
Turkanime gives "video list empty" error on any episode

### ISSUE THREAD

**Issue by glaicodes** [Kohi-den/extensions-source#414]
### Source information

Turkanime TV 14.25

### Source language

Turkish

### Steps to reproduce

1. Go to any anime
2. Try to open episode
3. See error

### Expected behavior

The episode should play

### Actual behavior

It gives video list empty error 

### Which app are you using?

Aniyomi

### App version

Preview r8019

### Android version

Android 15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by gr8vewalker** [comment]
Probably caused by an update. Before I updated the app it was just working fine.

After updating, I get this error:
```
12-15 22:27:32.405 12984 12984 E PlayerActivity: java.lang.ClassCastException: eu.kanade.tachiyomi.animeextension.tr.turkanime.TurkAnime$videoListParse$$inlined$parallelCatchingFlatMapBlocking$1 cannot be cast to kotlin.jvm.functions.Function2
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$4.invokeSuspend(Unknown Source:38)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.DispatchedTask.run(Unknown Source:110)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:154)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:28)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:59)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.animeextension.tr.turkanime.TurkAnime.videoListParse(TurkAnime.kt:594)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.animesource.online.AnimeHttpSource$$ExternalSyntheticLambda0.invoke(Unknown Source:66)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.source.online.HttpSource$$ExternalSyntheticLambda1.call(SourceFile:14)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(Unknown Source:2)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(Unknown Source:12)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(Unknown Source:31)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.Subscriber.setProducer(Unknown Source:38)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(Unknown Source:2)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.Subscriber.setProducer(Unknown Source:21)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(Unknown Source:18)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.Observable.unsafeSubscribe(Unknown Source:9)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeDoOnEach.call(SourceFile:2)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeDoOnEach.call(SourceFile:1)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.Observable.unsafeSubscribe(Unknown Source:9)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeMap.call(SourceFile:4)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeMap.call(SourceFile:1)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeLift.call(SourceFile:4)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeLift.call(SourceFile:1)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.Observable.subscribe(SourceFile:24)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at tachiyomi.core.common.util.lang.RxCoroutineBridgeKt.awaitSingle(Unknown Source:27)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.animesource.online.AnimeHttpSource.getVideoList(Unknown Source:4)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.ui.player.loader.EpisodeLoader$Companion.isHttp(Unknown Source:78)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.ui.player.loader.EpisodeLoader$Companion.getLinks(Unknown Source:45)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.ui.player.PlayerViewModel.init(Unknown Source:386)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.ui.player.PlayerActivity$onNewIntent$1.invokeSuspend(Unknown Source:97)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at eu.kanade.tachiyomi.ui.player.PlayerActivity$onNewIntent$1.invoke(Unknown Source:12)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Unknown Source:18)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Unknown Source:51)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:0)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at tachiyomi.core.common.util.lang.CoroutinesExtensionsKt$launchNonCancellable$1.invokeSuspend(Unknown Source:30)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.DispatchedTask.run(Unknown Source:110)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:62)
12-15 22:27:32.405 12984 12984 E PlayerActivity: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
12-15 22:27:32.405 12984 12984 E PlayerActivity:        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(Unknown Source:19)
12-15 22:27:32.405 12984 12984 E PlayerActivity:        ... 32 more
```
